services:
  #################################################
  # DB (MySQL)
  #################################################
  db:
    image: "mysql:8.0"
    volumes:
      - uber_clone_mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/uber_clone_DB_DATABASE
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/uber_clone_DB_PASSWORD
      MYSQL_PASSWORD_FILE: /run/secrets/uber_clone_DB_PASSWORD
      MYSQL_USER_FILE: /run/secrets/uber_clone_DB_USERNAME
    secrets:
      - uber_clone_DB_DATABASE
      - uber_clone_DB_PASSWORD
      - uber_clone_DB_USERNAME
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 20s
    networks:
      - uber_clone
  ##################################################
  # REDIS
  ##################################################
  redis:
    image: "redis:7.4"
    volumes:
      - "uber_clone_redis_data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 20s
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/uber_clone_REDIS_PASSWORD
    secrets:
      - uber_clone_REDIS_PASSWORD
    command: sh -c 'redis-server --appendonly yes --requirepass $$(cat /run/secrets/uber_clone_REDIS_PASSWORD | tr -d " \t\n\r")'
    networks:
      - uber_clone
  #################################################
  # OCTANE:FRANKENPHP
  #################################################
  app:
    image: ghcr.io/y-l-g/uber-clone-vue-laravel-map-back:main
    volumes:
      - uber_clone_app_data:/data
      - uber_clone_app_config:/config
    healthcheck:
      test: ["CMD", "php", "artisan", "octane:status"]
      start_period: 20s
    command: sh -c 'php artisan octane:frankenphp --host=0.0.0.0'
    environment:
      - APP_NAME=uber_clone
    secrets:
      - uber_clone_DB_DATABASE
      - uber_clone_DB_PASSWORD
      - uber_clone_DB_USERNAME
      - uber_clone_REDIS_PASSWORD
      - uber_clone_APP_URL
      - uber_clone_APP_KEY
      - uber_clone_REVERB_APP_SECRET
      - uber_clone_REVERB_APP_KEY
      - uber_clone_REVERB_APP_ID
      - uber_clone_APP_DOMAIN
      - uber_clone_MAIL_HOST
      - uber_clone_MAIL_USERNAME
      - uber_clone_MAIL_PASSWORD
      - uber_clone_MAIL_FROM_ADDRESS
    entrypoint: start-container
    networks:
      - uber_clone
      - caddy_network
  ##################################################
  # REVERB
  ##################################################
  reverb:
    image: ghcr.io/y-l-g/uber-clone-vue-laravel-map-back:main
    volumes:
      - uber_clone_reverb_data:/data
      - uber_clone_reverb_config:/config
    command: ["php", "artisan", "reverb:start", "--debug"]
    secrets:
      - uber_clone_DB_DATABASE
      - uber_clone_DB_PASSWORD
      - uber_clone_DB_USERNAME
      - uber_clone_REDIS_PASSWORD
      - uber_clone_APP_URL
      - uber_clone_APP_KEY
      - uber_clone_REVERB_APP_SECRET
      - uber_clone_REVERB_APP_KEY
      - uber_clone_REVERB_APP_ID
      - uber_clone_APP_DOMAIN
      - uber_clone_MAIL_HOST
      - uber_clone_MAIL_USERNAME
      - uber_clone_MAIL_PASSWORD
      - uber_clone_MAIL_FROM_ADDRESS
    entrypoint: start-container
    environment:
      - APP_NAME=uber_clone
    healthcheck:
      test: ["CMD", "pgrep", "-f", "reverb:start"]
      start_period: 10s
    networks:
      - uber_clone
      - caddy_network
  ##################################################
  # Frontend
  ##################################################
  frontend:
    image: ghcr.io/y-l-g/uber-clone-vue-laravel-map-front:main
    volumes:
      - uber_clone_frontend_data:/data
      - uber_clone_frontend_config:/config
    secrets:
      - uber_clone_APP_URL
      - uber_clone_REVERB_APP_KEY
      - uber_clone_APP_DOMAIN
      - uber_clone_VITE_APP_GOOGLE_MAPS_API_KEY
    environment:
      - APP_NAME=uber_clone
    entrypoint: start-container
    command: sh -c 'caddy run --config /etc/caddy/Caddyfile --adapter caddyfile'
    networks:
      - uber_clone
      - caddy_network
  ##################################################
  # HORIZON
  ##################################################
  horizon:
    image: ghcr.io/y-l-g/uber-clone-vue-laravel-map-back:main
    volumes:
      - uber_clone_horizon_data:/data
      - uber_clone_horizon_config:/config
    command: ["php", "artisan", "horizon"]
    healthcheck:
      test: ["CMD", "php", "artisan", "horizon:status"]
    secrets:
      - uber_clone_DB_DATABASE
      - uber_clone_DB_PASSWORD
      - uber_clone_DB_USERNAME
      - uber_clone_REDIS_PASSWORD
      - uber_clone_APP_URL
      - uber_clone_APP_KEY
      - uber_clone_REVERB_APP_SECRET
      - uber_clone_REVERB_APP_KEY
      - uber_clone_REVERB_APP_ID
      - uber_clone_APP_DOMAIN
      - uber_clone_MAIL_HOST
      - uber_clone_MAIL_USERNAME
      - uber_clone_MAIL_PASSWORD
      - uber_clone_MAIL_FROM_ADDRESS
    entrypoint: start-container
    environment:
      - APP_NAME=uber_clone
    networks:
      - uber_clone
  ##################################################
  # VOLUMES
  ##################################################
volumes:
  uber_clone_app_data:
  uber_clone_app_config:
  ##################################################
  uber_clone_mysql_data:
  uber_clone_redis_data:
  ##################################################
  uber_clone_reverb_data:
  uber_clone_reverb_config:
  ##################################################
  uber_clone_frontend_data:
  uber_clone_frontend_config:
  ##################################################
  uber_clone_horizon_data:
  uber_clone_horizon_config:
  ##################################################
secrets:
  uber_clone_DB_DATABASE:
    external: true
  uber_clone_DB_PASSWORD:
    external: true
  uber_clone_DB_USERNAME:
    external: true
  uber_clone_REDIS_PASSWORD:
    external: true
  uber_clone_APP_URL:
    external: true
  uber_clone_APP_KEY:
    external: true
  uber_clone_REVERB_APP_SECRET:
    external: true
  uber_clone_REVERB_APP_KEY:
    external: true
  uber_clone_REVERB_APP_ID:
    external: true
  uber_clone_APP_DOMAIN:
    external: true
  uber_clone_VITE_APP_GOOGLE_MAPS_API_KEY:
    external: true
  uber_clone_MAIL_HOST:
    external: true
  uber_clone_MAIL_USERNAME:
    external: true
  uber_clone_MAIL_PASSWORD:
    external: true
  uber_clone_MAIL_FROM_ADDRESS:
    external: true
networks:
  uber_clone:
    driver: overlay
    attachable: true
  caddy_network:
    external: true
