services:
  #################################################
  # OCTANE:FRANKENPHP
  #################################################
  app:
    image: ghcr.io/y-l-g/uber-clone-vue-laravel-map-back:main
    volumes:
      - uber_clone_app_data:/data
      - uber_clone_app_config:/config
    healthcheck:
      test: ["CMD", "php", "artisan", "octane:status"]
      start_period: 20s
    command: sh -c 'php artisan octane:frankenphp --host=0.0.0.0'
    environment:
      - APP_NAME=uber_clone
    secrets:
      - uber_clone_DB_PASSWORD
      - uber_clone_REDIS_PASSWORD
      - uber_clone_APP_URL
      - uber_clone_APP_KEY
      - uber_clone_REVERB_APP_SECRET
      - uber_clone_REVERB_APP_KEY
      - uber_clone_REVERB_APP_ID
      - uber_clone_APP_DOMAIN
      - uber_clone_MAIL_HOST
      - uber_clone_MAIL_USERNAME
      - uber_clone_MAIL_PASSWORD
      - uber_clone_MAIL_FROM_ADDRESS
    entrypoint: start-container
    networks:
      - uber_clone
  ##################################################
  # REVERB
  ##################################################
  reverb:
    image: ghcr.io/y-l-g/uber-clone-vue-laravel-map-back:main
    volumes:
      - uber_clone_reverb_data:/data
      - uber_clone_reverb_config:/config
    command: ["php", "artisan", "reverb:start", "--debug"]
    secrets:
      - uber_clone_DB_PASSWORD
      - uber_clone_REDIS_PASSWORD
      - uber_clone_APP_URL
      - uber_clone_APP_KEY
      - uber_clone_REVERB_APP_SECRET
      - uber_clone_REVERB_APP_KEY
      - uber_clone_REVERB_APP_ID
      - uber_clone_APP_DOMAIN
      - uber_clone_MAIL_HOST
      - uber_clone_MAIL_USERNAME
      - uber_clone_MAIL_PASSWORD
      - uber_clone_MAIL_FROM_ADDRESS
    entrypoint: start-container
    environment:
      - APP_NAME=uber_clone
    healthcheck:
      test: ["CMD", "pgrep", "-f", "reverb:start"]
      start_period: 10s
    networks:
      - uber_clone
  ##################################################
  # Frontend
  ##################################################
  frontend:
    image: ghcr.io/y-l-g/uber-clone-vue-laravel-map-front:main
    volumes:
      - uber_clone_frontend_data:/data
      - uber_clone_frontend_config:/config
    secrets:
      - uber_clone_APP_URL
      - uber_clone_REVERB_APP_KEY
      - uber_clone_APP_DOMAIN
      - uber_clone_VITE_APP_GOOGLE_MAPS_API_KEY
    environment:
      - APP_NAME=uber_clone
    entrypoint: start-container
    command: sh -c 'caddy run --config /etc/caddy/Caddyfile --adapter caddyfile'
    networks:
      - uber_clone
  ##################################################
  # HORIZON
  ##################################################
  horizon:
    image: ghcr.io/y-l-g/uber-clone-vue-laravel-map-back:main
    volumes:
      - uber_clone_horizon_data:/data
      - uber_clone_horizon_config:/config
    command: ["php", "artisan", "horizon"]
    healthcheck:
      test: ["CMD", "php", "artisan", "horizon:status"]
    secrets:
      - uber_clone_DB_PASSWORD
      - uber_clone_REDIS_PASSWORD
      - uber_clone_APP_URL
      - uber_clone_APP_KEY
      - uber_clone_REVERB_APP_SECRET
      - uber_clone_REVERB_APP_KEY
      - uber_clone_REVERB_APP_ID
      - uber_clone_APP_DOMAIN
      - uber_clone_MAIL_HOST
      - uber_clone_MAIL_USERNAME
      - uber_clone_MAIL_PASSWORD
      - uber_clone_MAIL_FROM_ADDRESS
    entrypoint: start-container
    environment:
      - APP_NAME=uber_clone
    networks:
      - uber_clone
  ##################################################
  # VOLUMES
  ##################################################
volumes:
  uber_clone_app_data:
  uber_clone_app_config:
  ##################################################
  uber_clone_reverb_data:
  uber_clone_reverb_config:
  ##################################################
  uber_clone_frontend_data:
  uber_clone_frontend_config:
  ##################################################
  uber_clone_horizon_data:
  uber_clone_horizon_config:
  ##################################################
secrets:
  uber_clone_DB_PASSWORD:
    external: true
  uber_clone_REDIS_PASSWORD:
    external: true
  uber_clone_APP_URL:
    external: true
  uber_clone_APP_KEY:
    external: true
  uber_clone_REVERB_APP_SECRET:
    external: true
  uber_clone_REVERB_APP_KEY:
    external: true
  uber_clone_REVERB_APP_ID:
    external: true
  uber_clone_APP_DOMAIN:
    external: true
  uber_clone_VITE_APP_GOOGLE_MAPS_API_KEY:
    external: true
  uber_clone_MAIL_HOST:
    external: true
  uber_clone_MAIL_USERNAME:
    external: true
  uber_clone_MAIL_PASSWORD:
    external: true
  uber_clone_MAIL_FROM_ADDRESS:
    external: true
networks:
  uber_clone:
    external: true
